### ISSUE TITLE
'Type MyController is not assignable to type 'ConvectorController<any>'

### ISSUE THREAD

**Issue by floatingpoint32** [hyperledger-labs/convector#111]
## The problem

I have built a smart contract to store and authenticate users, which has been fully unit tested and thus works just fine when ran as tests. However, when I try to package the chaincode to install it into my fabric network, I get the following error:

https://i.imgur.com/mEi5f4G.png

I am building my project on top of: https://github.com/worldsibu/convector-example-fabcar-rest

## Environment

* Convector version (or git revision) that exhibits the issue:
  - conv-rest-api: 0.1.1
  - convector-adapter-mock: 1.3.6
  - convector-platform-fabric 1.3.6

* OS/version: Ubuntu 19.04
* Node.js version: v10.15.2
* Npm or Yarn package manager: Npm

## Code To Reproduce Issue [ Good To Have ]

```typescript
import * as yup from 'yup';
import {
  Controller,
  ConvectorController,
  Invokable,
  Param
} from '@worldsibu/convector-core';
import * as uuid from 'uuid/v4';
import * as bcrypt from "bcryptjs";
import * as jwt from "jsonwebtoken";
import { User } from './user.model';

const JWT_SECRET = "SOME TOKEN";

@Controller('user')
export class UserController extends ConvectorController<any> {
  @Invokable()
  public async init() {
    ..
  }

  @Invokable()
  public async create(@Param(User) user: User) {
    ..
  }

  @Invokable()
  public async authenticate(@Param(yup.string()) username: string, @Param(yup.string()) password: string): Promise<any> {
    ..
  }

  @Invokable()
  public async queryOne(@Param(yup.string()) id: string): Promise<User> {
    ..
  }

  @Invokable()
  public async getAll(): Promise<User[]> {
    ..
  }
}
```

Line 21 in the image refers to:

```typescript
export const UserControllerBackEnd = 
    ClientFactory(UserController, adapter);

export const CompanyControllerBackEnd = 
    ClientFactory(CompanyController, adapter);
```

Related stackoverflow link: https://stackoverflow.com/questions/58823028/how-to-fix-type-mycontroller-is-not-assignable-to-type-convectorcontrollerany

**Comment by DanielKillenberger** [comment]
I just fixed the issue with double checking all the versions being consistent in both the chaincode and the client making requests to it.
Delete also the package-lock.json to make sure it's not using old versions.
Hope this helps.
