### ISSUE TITLE
Direct access to Stub

### ISSUE THREAD

**Issue by walmon** [hyperledger-labs/convector#34]
Even if the stub can be directly accessed, it's not an explicit task. We have found that this is a rather common need.

```
const stub = (BaseStorage.current as any).stubHelper;
```

This `as any` is because it's a private property, so Typescript will mark it as incorrect.

We have working examples of it here: https://github.com/worldsibu/convector-identity-patterns/blob/master/packages/participant-cc/src/participant.controller.ts#L18

**Comment by diestrin** [comment]
Controller can now do:
```ts
@Controller('token')
export class TokenController extends ConvectorController<ChaincodeTx> {
  @Invokable()
  public async getIdentityInfo() {
    const mspId = this.tx.identity.getMSPID();
    const cert = this.tx.identity.getX509Certificate();
    const subject = cert.subject.commonName;
    const issuer = cert.issuer.commonName;

    return `Cert Fingerprint ${this.sender} for ${subject} (${mspId}) issued by ${issuer}`;
  }
}
```
