### ISSUE TITLE
Support ConvectorComplexType<MyComplexType> similar to ConvectorModel<MyType>

### ISSUE THREAD

**Issue by bentoo42** [hyperledger-labs/convector#41]
Currently, if a class inherits from ConvectorModel<MyType>: 

export class Account extends ConvectorModel<Account>
and
@Validate(Account)

However, if you have classes that don't inherit from ConvectorModel<MyType>, it is quite cumbersome.

export interface ContentItem {
  value: any;
  name: string;
}

export const ContentItem = yup.object<ContentItem>({
  value: yup.mixed().required(),
  name: yup.string().required()
});

I propose that you support:

class MyComplexType extends ConvectorComplexType<MyComplexType>

**Comment by diestrin** [comment]
We don't actually need another kind of model. ConvectorModel already has an schema build with the decorators, with the merge of #46 you can now declare a ConvectorModel with your complex structure and apply it with `@Validate` https://github.com/hyperledger-labs/convector/blob/b712adae843a5020aec11c25c640d69c2d1fb708/examples/token/src/token.model.ts#L52-L53 and with #44 we have now inheritance for models as well.

This is expected to be released next Tuesday.

**Comment by bentoo42** [comment]
Does it support circular dependencies?

Brian Bentow
Head of Innovation
T: (949) 945-2515
M: (818) 825-8805
(866) INSTAMED
www.instamed.com
________________________________
