### ISSUE TITLE
FlatConvectorModel with optional properties

### ISSUE THREAD

**Issue by friendly-tech** [hyperledger-labs/convector#56]
## The problem

When using a FlatConvectorModel<T> and T has optional properties, you are not able to assign T to the property.

[See here for example](https://stackblitz.com/edit/convector-acdcbj?file=user.controller.ts)

### Current Behavior

A compiler error when assigning T to FlatConvectorModel<T>

### Expected Behavior

It should cater for optional properties

## Code To Reproduce Issue [ Good To Have ]

```
class TestModel extends ConvectorModel<TestModel> {
  public type = 'io.worldsibu.test';

  @Validate(yup.string())
  public name: string;

  @Validate(yup.number())
  public optionalProperty?: number;
}

class TestFlatModel extends ConvectorModel<TestFlatModel> {
  public type = 'io.worldsibu.test2';

  @Validate(TestModel)
  public child: FlatConvectorModel<TestModel>;

}

var item = new TestModel();
var parent = new TestFlatModel();
parent.child = item; //Compiler error here..

```

**Comment by b3of** [comment]
Have you checked [this](https://github.com/hyperledger-labs/convector/pull/44)? might help.
