### ISSUE TITLE
When unit testing: transaction timestamp is 0

### ISSUE THREAD

**Issue by raphabenoi** [hyperledger-labs/convector#77]
## The problem

Just a little problem I came accross. Don't no if it's just happening for me but thought it might be relevant:

When debugging my chaincode as explained in the tutorial [from @waltermontes](https://medium.com/worldsibu/testing-and-debugging-a-convector-smart-contract-aa02c84e7ecc) I get a `txTimestamp = 0` when using this line in my code: `const txTimestamp = this.tx.stub.getTxDate().getTime();`

It's not that big of a deal since I can temporarily change it by hand for testing, but maybe it's just a small thing to change that could make life easier in the future :smiley:

## Environment

* Convector version 1.3.3
* OS/version: macOS Mojave Version 10.14.3
* Node.js version: 8.15.0
* Npm package manager: 6.4.1
* Convector CLI version: 1.1.3 
* Hurley CLI version: 1.0.1

### Expected Behavior

Ideally, the `txTimetamp` returned by `this.tx.stub.getTxDate().getTime()` equals `Date.now()` of the moment of invokation of the chaincode and not `=0`

**Comment by diestrin** [comment]
This is a problem with the MockStub library. I created an issue in their repo wearetheledger/fabric-mock-stub#24

**Comment by raphabenoi** [comment]
Ok, thanks! Then this one can be closed!
