### ISSUE TITLE
Not getting expected output when invoking contract method from Nodejs code. However works fine with `hurl` cli

### ISSUE THREAD

**Issue by Vishwas1** [hyperledger-labs/convector#80]
## The problem

I try to invoke a method called `create(@Param(Manager)  manager: Manager)` via Nodejs codebase, its getting successful(and I see log in docker container), Now, If I call `get(@Param(yup.string()) id: string)` method from nodejs code in order to retrive the object, what I get in return is just `{"type":"io.worldsibu.manager"}`, not the atual `Manager` object..... however If I use `hurl` to call the create method (like this `hurl invoke manager manager_create '{"id":"b2abcde","type":"io.worldsibu.manager","name":"Test","created":1554892232910,"modified":1554892232910}'`) and then if I use `get` method, I am able to retrive the expected object as `"{"id":"b2abcde","type":"io.worldsibu.manager","name":"Test","created":1554892232910,"modified":1554892232910}"`.

I have also check the docker container log in both the situations, there is not difference in both the `creates` calls.

## Environment

* Convector version (or git revision) that exhibits the issue:
* Last Convector version that did not exhibit the issue (if applicable):
* OS/version: Ubuntu 16.04
* Node.js version:v10.15.3
* Npm or Yarn package manager: npm 6.4.1
* Convector CLI version (if applicable): 1.1.3
* Hurley CLI version (if applicable): 1.0.4

### Current Behavior

Getting `{"type":"io.worldsibu.manager"}` as output.

### Expected Behavior

Should return `{"id":"b2abcde","type":"io.worldsibu.manager","name":"Test","created":1554892232910,"modified":1554892232910}"` as output

## Code To Reproduce Issue [ Good To Have ]

This is how I am calling `create` method
```

const create = async (req, res) => {
  try {
    const modelSample = new Manager({
      id: uuid(),
      name: 'Test',
      created: Date.now(),
      modified: Date.now(),
    });
    console.log(modelSample.id);
    await ManagerControllerBackEnd.create(modelSample);
    
    res.status(200).json(JSON.stringify('SUCCESS'));
  } catch (err) {
    console.log(err);
    res.status(500).json(err);
  }
}
```

Note*:
- I am able to get the expected result if I use `hurl` cli.
- I also noticed the docker container log, in both the cases it is the same

**Comment by walmon** [comment]
Hi @vishwas1 you are not using the supported node version as stated in the readmes and https://docs.worldsibu.com/article/89-tutorial note that that limitation comes from Fabrics SDK.

You can use NVM to have both versions.

Feel free to reopen if you get the issue again.
