### ISSUE TITLE
is this project is active ?

### ISSUE THREAD

**Issue by koptan** [hyperledger-labs/convector#87]
I like the work,effort here , and i am planing to use this framework in my next project .

But i am afraid that this project will be under development anymore .

So the question is : what is the road map for this project ?

Thank you .

**Comment by walmon** [comment]
Hi @koptan the project is still maintained if that's your questions. It's reached a stable stage so the new features are based on feedback and the official roadmap here: https://docs.worldsibu.com/article/97-roadmap 

Also, the community where most of the active devs are is here: https://discord.gg/twRwpWt
